### ISSUE TITLE
mancato aggiornamento national_typing_subtyping_influenza_viruses.csv

### ISSUE THREAD

**Issue by capmar00** [fbranda/influnet#6]
Buonasera,
il file data-aggregated/virological_data/national_typing_subtyping_influenza_viruses.csv è fermo alla settimana 3. Probabilmente l'aggiornamento di oggi non è andato a buon fine.
grazie

**Comment by fbranda** [comment]
Grazie per la segnalazione. Il bug è stato fixato!
